### ISSUE TITLE
feat: Config file load from the variant file dir

### ISSUE THREAD

**Issue by aroq** [mumoshu/variant#110]
## what
- Allow loading of a config file from the same dir as the variant file itself.

## why
- Variant command file can be located in the directory different from the current (working) dir. Sometimes it makes sense to keep the config in the same dir as the variant file for the convenience.

**Comment by mumoshu** [comment]
@aroq Hey!

I think variant already have it. Suppose you're running a variant command with `./mycmd foo`, values for keys under `foo:` in `./mycmd.yaml` are automatically loaded to populate the parameters.

**Comment by aroq** [comment]
@mumoshu Hey!

I meant that when you have a variant command file (not a task) not in the working dir, it makes send to try load config file from the same dir (not a working dir). I've updated the initial message in this thread to make it more clear.

**Comment by mumoshu** [comment]
@aroq Ah! That makes sense. I was considering to leverage some go template so that you can explicitly say `{{.variantCmdDir}}/config.yaml` to point the config file from the same dir.

**Comment by mumoshu** [comment]
...which is the goal of #58
