### ISSUE TITLE
feat: Set global params from environment variables

### ISSUE THREAD

**Issue by aroq** [mumoshu/variant#111]
## what
- Allow setting of the global variant params from the environment variables.

## why
- it is convenient to set the global variant params from the environment variables.

---

Global variant params:

```
-C, --color                        Colorize output (default true)
-c, --config-file string           Path to config file
-o, --output string                Output format. One of: json|text|bunyan (default "text")
-v, --verbose                      verbose output
```

**Comment by mumoshu** [comment]
@aroq Hey! Would you mind sharing in/out of this feature? Especially I'm unsure what `global file params` means here.

**Comment by aroq** [comment]
@mumoshu I've updated the original issue description to make it clear.

**Comment by mumoshu** [comment]
That makes sense. Thanks for clarifying!
