### ISSUE TITLE
Support --no-color option

### ISSUE THREAD

**Issue by Nuru** [mumoshu/variant#120]
`variant` 0.33.0 has ` --color` option, which is a boolean and defaults to true. Common practice in this case is to create boolean options that begin with `--no-` to set the flag to false. In this case `--no-color`. I thought `go` created those automatically, but for whatever reason, `variant` does not have them:
```
$ variant --color=false version
0.33.0
$ variant --no-color version
Error: unknown flag: --no-color
Run 'variant --help' for usage.
``` 
("Usage" output omitted from above output for brevity's sake)

Please add at least a `--no-color` option, and consider automatically creating `--no-` prefix options for all boolean options.

**Comment by mumoshu** [comment]
@Nuru Hey! I've added this in v0.34.0. Would you mind confirming?

**Comment by Nuru** [comment]
@mumoshu Thanks for adding `--no-color` and yes, it does work, and I do not want to sound ungrateful but you sort of did it wrong. The `usage` now has these lines (the rest omitted for the sake of brevity)
```
  -C, --color                        Colorize output (default true)
...
      --no-color                     Un-colorize output
```

The usage should be:
```
  -C, --[no-]color                        Colorize output (default true)
```
or
```
  -C, --[no-]color                        [Do not] Colorize output (default true)
```


By the way, the `-C` option is kind of weird, too. Generally a single dash, single letter boolean option toggles a setting from false to true. So having a single-letter option for a boolean option that defaults to `true` is odd. Still, if you want to have it, that is your call.

However, all the other single letter options that take arguments take them as a word following the option. For example:
```
$ variant -o json version
{"level":"info","msg":"0.34.0","time":"2019-09-08T18:55:57Z"}
```
The only way for the `-C` option to be useful is to take an argument that sets it to false, so that should be
```
$ variant -C false version
```
but that does not work. You have to use the equals syntax,
```
$ variant -C=false version
```
which is just not the standard convention for the single dash, single letter options. 

Frankly, I would drop the `-C` option because the short options are meant to be easy to type alternatives to the long option. There is no point to them if the short option does not do anything, which is the case here. If you want to keep it for backwards compatibility, I understand.

**Comment by mumoshu** [comment]
Hey!

> --[no-]color

Yeah I prefer this. The only thing is that I don't know how I could do it with cobra.
