### ISSUE TITLE
feat: GitHub Pull Request Comments interface

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#29]
Like #28, but the only difference is that it is for GitHub pull requests.

This may be implemented as an HTTP server that acts as an adapter between the GitHub Webhook and the varaint gRPC interface #31

**Comment by osterman** [comment]
Oh interesting... so you see this as potentially taking on a role similar to atlantis?

**Comment by mumoshu** [comment]
@osterman Basically that, but I imagine a more general one!

My idea is that we need a maintainable and universal cli that can be written easily, integrated to various workflows including github prs, potential to graduate(or transform) into a full-fledged cli written in golang.

**Comment by mumoshu** [comment]
You should use GitHub Actions v2 for ChatOps with Variant. See https://github.com/variantdev/variant-github-actions-demo for the demo.
