### ISSUE TITLE
feat: do not create files without user permission

### ISSUE THREAD

**Issue by osterman** [mumoshu/variant#39]
## what
* do not create `.env` files

## why
* `variant` automatically creates empty `.test.shenv` files
* these files might not even be used by the caller (E.g. if caller uses `direnv`)
* if unused, the pollute a workspace

**Comment by mumoshu** [comment]
Thanks for reporting! This will be fixed in the next release via 44ad64d92a9bf4cca2b6c7536aecd4c210eee549

**Comment by osterman** [comment]
Thanks @mumoshu !
