### ISSUE TITLE
feat: new releases cut on merge to master

### ISSUE THREAD

**Issue by osterman** [mumoshu/variant#43]
## what
* Release frequently so we can easily distribute current binaries

## why
* Love what you've been with `helmfile` with frequent releases
* Current binary releases make the tool accessible to a wider audience

**Comment by mumoshu** [comment]
Just released https://github.com/mumoshu/variant/releases/tag/v0.11.0 and set up my automated release script :)

https://github.com/mumoshu/variant/commit/6f1218ba7a6531eba4bfc1d4cc311b7a4f42a483

Future releases should be cut more frequently!

**Comment by osterman** [comment]
Thanks @mumoshu!! Much appreciated
