### ISSUE TITLE
More simplified logging

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#45]
The latest variant produces logs as follows:

```console
$ ./myfirstcmd bar
```

![image](https://user-images.githubusercontent.com/22009/51293760-86f01700-1a53-11e9-9c92-8ae87374e116.png)

The first line is an error message sent to STDERR. The second is a informational message sent to STDERR. The third line is the actual output written to the stdout by the user script.

`INFO[0000] ≫ sh -c echo "dude"` seems noisy. I'd rather want to see which variant app and task being executed and what logged what. The same thing can be said for the error message, too.

I'd change it to:

When the log level is WARN(default):

```console
myfirstcmd ≫ open .myfirstcmdenv: no such file or directory
Hello variant you are in the heaven
```

When the log level is INFO:

```
myfirstcmd ≫ open .myfirstcmdenv: no such file or directory
myfirstcmd ≫ starting myfirstcmd.foo
myfirstcmd.foo ≫ Hello variant you are in the heaven`
Hello variant you are in the heaven
```

The first line should be colored RED, while the second and the third should be colored LIGHT BLUE.

Note that #39, which should clear `open .myfirstcmdenv: no such file or directory` once fixed, is an another story :)

What I want to talk here is more about what and how to log on what level.

**Comment by osterman** [comment]
Yes, I think this would make it more user-friendly!
