### ISSUE TITLE
Variant creates .env files in current working directory every time it is run

### ISSUE THREAD

**Issue by Nuru** [mumoshu/variant#64]
Every time `variant` is run, it creates a `".${0}env"` file in the current working directory. This is horrible littering and should never happen.

```
$> ls -A
variant*
$> ./variant > /dev/null
$> ls -A
.variantenv	variant*
```

**Comment by mumoshu** [comment]
@Nuru Hey! Thanks for reporting. This will be fixed in the next release via 44ad64d92a9bf4cca2b6c7536aecd4c210eee549
